### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by IceDBorn** [IceDBorn/pipewire-screenaudio#31]
## 0.3.3
- [x] js code cleanup (#29)
- [ ] bash code cleanup (#30)
- [ ] Add logging (#30)

## 0.4.0
- [ ] [React/MUI port](https://github.com/IceDBorn/pipewire-screenaudio/tree/react-mui-port)
- [ ] Separate bash function for All Desktop Audio
- [ ] Native messages syntax: `'[{ key: value }]'` -> `'{ key: value }'`
- [x] Multiple nodes selection

## 0.4.1
- [ ] Native health checks

## 1.0.0
- [ ] Replace pw-cli with a bash pipewire client or a wireplumber client in lua
